CXX = swiftc
APPNAME = A2SimpleNavigatorSwift
BUILD = buildA2
DOCS = docsA2

all: install

install:
	$(CXX) A2_SimpleNavigator_Swift/A2_SimpleNavigator_Swift/*.swift -o $(APPNAME)
	./$(APPNAME)

clean:
	

tests:
	

s21_graph:
	

s21_graph_algorithms:
	

